spring:
  application:
    name: gateway-server
server:
  port: 5003
zuul:
  sensitive-headers:
  routes:
    webService:
      path: /provide/**
      serviceId: provide-server
    appService:
      path: /consumer/**
      serviceId: consumer-server

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5000/eureka/
  instance:
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${eureka.instance.appname}}:5003
    appname: gateway-server

