spring:
  application:
    name: auth2-server
  #redis配置数据
  redis:
    hostName: 117.73.8.227
    port: 6379
    database: 0
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 5000
server:
  port: 5005
#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5000/eureka/
  instance:
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${eureka.instance.appname}:5001
    appname: auth2-server
security:
  oauth2:
    resource:
      filter-order: 3
